import type { McpDesign, ToolCandidate, ValidationReport } from '../types.js';

/** Render a human-readable design + rationale document. */
export function emitMarkdown(design: McpDesign, report: ValidationReport): string {
  const lines: string[] = [];
  const d = design;

  lines.push(`# MCP Server Design — ${d.server.name}`, '');
  lines.push(`> ${d.server.description}`, '');
  lines.push(
    `Generated by **${d.meta.generator}** (${d.meta.mode} mode) on ${d.meta.generatedAt}.`,
    `Built from **${d.meta.questionCount}** eval questions over **${d.meta.endpointCount}** documented endpoints.`,
    '',
  );

  lines.push('## Server', '');
  lines.push(`- **Name:** ${d.server.name}`);
  lines.push(`- **Transport:** ${d.server.transport}`);
  lines.push(`- **Auth:** ${d.auth.type}${d.auth.envVar ? ` (env: \`${d.auth.envVar}\`)` : ''}`);
  if (d.auth.scopes?.length) lines.push(`- **Scopes:** ${d.auth.scopes.join(', ')}`);
  lines.push('');

  lines.push('## Coverage summary', '');
  lines.push(`- **Questions covered:** ${report.coverage.filter((c) => c.coveredByTool).length}/${report.coverage.length} (${Math.round(report.coverageRate * 100)}%)`);
  if (report.uncovered.length) lines.push(`- **Uncovered:** ${report.uncovered.join(', ')}`);
  if (report.godTools.length) lines.push(`- **Tools flagged broad (review):** ${report.godTools.join(', ')}`);
  if (report.orphanTools.length) lines.push(`- **Orphan tools:** ${report.orphanTools.join(', ')}`);
  if (report.unknownEndpointRefs.length) lines.push(`- **Unknown endpoint refs:** ${report.unknownEndpointRefs.join(', ')}`);
  lines.push('');

  lines.push('## Tools', '');
  lines.push(`The forge produced **${d.tools.length}** task-oriented tools. Each wraps one or more API`);
  lines.push('endpoints so a question is answered in a single tool call rather than many round-trips.', '');
  for (const t of d.tools) lines.push(...renderTool(t));

  lines.push('## Resources', '');
  for (const r of d.resources) lines.push(`- **${r.name}** — ${r.description}`);
  lines.push('');

  lines.push('## Prompts', '');
  for (const p of d.prompts) lines.push(`- **${p.name}** — ${p.description}`);
  lines.push('');

  lines.push('## Eval coverage matrix', '');
  lines.push('| Question | Intent / prompt | Covered by | Confidence | Notes |');
  lines.push('|---|---|---|---|---|');
  for (const row of report.coverage) {
    lines.push(
      `| ${row.questionId} | ${escapeCell(row.prompt)} | ${row.coveredByTool ?? '—'} | ${row.confidence.toFixed(2)} | ${escapeCell(row.notes)} |`,
    );
  }
  lines.push('');

  lines.push('## Review checklist', '');
  lines.push('- [ ] Every uncovered question has a planned tool or is out of scope.');
  lines.push('- [ ] Broad/god tools are split or justified.');
  lines.push('- [ ] HTML-derived endpoints verified against real API behavior.');
  lines.push('- [ ] Auth scheme and scopes confirmed.');
  lines.push('- [ ] Pagination/rate-limit/partial-result behavior acceptable per tool.');
  lines.push('');

  return lines.join('\n');
}

function renderTool(t: ToolCandidate): string[] {
  const out: string[] = [];
  out.push(`### \`${t.name}\``, '');
  out.push(t.description, '');
  out.push(`- **Entities:** ${t.entities.join(', ') || '—'}`);
  out.push(`- **Covers questions:** ${t.evalCoverage.join(', ') || '—'}`);
  if (t.reviewFlags.length) out.push(`- **⚠ Review:** ${t.reviewFlags.join('; ')}`);
  out.push('');
  out.push('**Underlying API calls (in order):**', '');
  t.underlyingCalls.forEach((c, i) => {
    const extra: string[] = [];
    if (c.foreach) extra.push(`foreach \`${c.foreach}\``);
    if (c.condition) extra.push(`if \`${c.condition}\``);
    if (c.concurrency) extra.push(`concurrency ${c.concurrency}`);
    if (c.maxItems) extra.push(`max ${c.maxItems}`);
    const suffix = extra.length ? ` _(${extra.join(', ')})_` : '';
    out.push(`${i + 1}. \`${c.endpoint}\` — ${c.purpose}${suffix}`);
  });
  out.push('');
  out.push('**Input schema:** `' + schemaSummary(t.inputSchema) + '`');
  out.push('');
  out.push('**Output schema:** `' + schemaSummary(t.outputSchema) + '`');
  out.push('');
  return out;
}

function schemaSummary(schema: { properties?: Record<string, unknown>; type: string }): string {
  const props = schema.properties ? Object.keys(schema.properties) : [];
  return `${schema.type}{ ${props.join(', ')} }`;
}

function escapeCell(s: string): string {
  return (s ?? '').replace(/\|/g, '\\|').replace(/\n/g, ' ').slice(0, 120);
}
