import yaml from 'js-yaml';
import type { McpDesign } from '../types.js';

/** Serialize the design to canonical YAML, dropping undefined keys. */
export function emitYaml(design: McpDesign): string {
  const clean = JSON.parse(JSON.stringify(design));
  const header =
    '# MCP server design — generated by mcp-spec-forge\n' +
    '# Canonical, machine-readable spec. See mcp-design.md for rationale.\n';
  return header + yaml.dump(clean, { lineWidth: 100, noRefs: true, sortKeys: false });
}
