import type { McpDesign, ToolCandidate } from '../types.js';

/**
 * Emit a minimal, runnable TypeScript MCP server scaffold from the design.
 * Tool handlers are stubs that document the intended underlying API calls.
 * Returns a map of relative file path -> file contents.
 */
export function scaffoldServer(design: McpDesign): Record<string, string> {
  const files: Record<string, string> = {};

  files['package.json'] = JSON.stringify(
    {
      name: design.server.name,
      version: design.server.version,
      type: 'module',
      bin: { [design.server.name]: 'src/server.ts' },
      scripts: { start: 'tsx src/server.ts' },
      dependencies: { '@modelcontextprotocol/sdk': '^1.0.0' },
      devDependencies: { tsx: '^4.19.1', typescript: '^5.6.2', '@types/node': '^22.7.4' },
    },
    null,
    2,
  );

  files['README.md'] =
    `# ${design.server.name}\n\n${design.server.description}\n\n` +
    `Scaffold generated by mcp-spec-forge. Implement each tool handler in \`src/tools/\` ` +
    `by calling the documented underlying API endpoints. Auth: \`${design.auth.type}\`` +
    `${design.auth.envVar ? ` via env \`${design.auth.envVar}\`` : ''}.\n`;

  files['src/server.ts'] = serverEntry(design);
  files['src/api/client.ts'] = apiClient(design);
  for (const tool of design.tools) {
    files[`src/tools/${tool.name}.ts`] = toolModule(tool);
  }
  files['src/tools/index.ts'] =
    design.tools.map((t) => `export { ${t.name} } from './${t.name}.js';`).join('\n') + '\n';

  return files;
}

function serverEntry(design: McpDesign): string {
  const imports = design.tools.map((t) => t.name).join(', ');
  const registrations = design.tools
    .map(
      (t) => `  server.registerTool(
    ${JSON.stringify(t.name)},
    {
      description: ${JSON.stringify(t.description)},
      inputSchema: ${t.name}.inputSchema,
    },
    ${t.name}.handler,
  );`,
    )
    .join('\n');

  return `import { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { StdioServerTransport } from '@modelcontextprotocol/sdk/server/stdio.js';
import { ${imports} } from './tools/index.js';

const server = new McpServer({ name: ${JSON.stringify(design.server.name)}, version: ${JSON.stringify(design.server.version)} });

${registrations}

const transport = new StdioServerTransport();
await server.connect(transport);
`;
}

function apiClient(design: McpDesign): string {
  const env = design.auth.envVar ?? 'API_TOKEN';
  return `const TOKEN = process.env[${JSON.stringify(env)}];

export async function apiCall(method: string, path: string, opts: { query?: Record<string, unknown>; body?: unknown } = {}) {
  const url = new URL(path, process.env.API_BASE_URL ?? 'https://api.example.com');
  for (const [k, v] of Object.entries(opts.query ?? {})) {
    if (v !== undefined && v !== null) url.searchParams.set(k, String(v));
  }
  const res = await fetch(url, {
    method,
    headers: {
      'content-type': 'application/json',
      ${design.auth.type === 'none' ? '' : `authorization: \`Bearer \${TOKEN}\`,`}
    },
    body: opts.body ? JSON.stringify(opts.body) : undefined,
  });
  if (!res.ok) throw new Error(\`API \${method} \${path} failed: \${res.status}\`);
  return res.json();
}
`;
}

function toolModule(tool: ToolCandidate): string {
  const calls = tool.underlyingCalls
    .map((c) => `  //  - ${c.endpoint} :: ${c.purpose}${c.foreach ? ` (foreach ${c.foreach})` : ''}`)
    .join('\n');
  return `import { apiCall } from '../api/client.js';

// Auto-generated stub. Implement the orchestration described below.
export const ${tool.name} = {
  inputSchema: ${JSON.stringify(tool.inputSchema, null, 2)} as const,

  // Underlying API calls this tool should orchestrate (in order):
${calls || '  //  (no calls resolved)'}
  async handler(args: Record<string, unknown>) {
    // TODO: orchestrate the underlying calls above, collapsing list-then-detail
    // patterns into a single response. Respect max_items / include_details inputs.
    void apiCall;
    void args;
    return { content: [{ type: 'text', text: 'Not implemented: ${tool.name}' }] };
  },
};
`;
}
